rvm:
- 2.0.0
deploy:
  provider: heroku
  api_key:
    secure: wMoEfuwYGWwcR/YXmc6vXawJqxT6Zo8xJxwZcUqkPjCvSG+SydM7kz2FjInFaiGnoWbhVpvF3WmdqAujaJwhEFI0r2p4WZ8BxvusdCFuVghV55QjrfVe4bzsf9dabYDEK2b8tm51xZZzkULwwA30tcURG5Pp1sz+yT7VH3VxAYs=
  app: learnhowtoprogram
  on:
    repo: epicodus/textbook
