rvm:
- 2.0.0
deploy:
  provider: heroku
  api_key:
    secure: rZNcyNjt4dgRSTLrgp740fxdgvcdEIsx10EFHc/T0NH4YjRcBqmsVmEkzw2RHds2/BzGbQ6PZSzGAc0Sx2f+6cs0jrhj6hdHgDZqlWHUddytZHrTnxfE1ff/Ja4Pwpz/aHmKPqmoSccQRDJvDxaA7aYh/IBIOhCxK/VUUGGPB54=
  app: learnhowtoprogram
  on:
    repo: epicodus/textbook
